<a href="https://colab.research.google.com/github/ksarpe/PyTorchLearn/blob/main/pytorch_learn0.0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cu118


## PYTORCH POCZĄTKI

#1. scalar


In [4]:
scalar = torch.tensor(7)
scalar

torch.Size([])

# 2. vector

In [13]:
vector = torch.tensor([3, 3])
vector.ndim

1

# 3. MATRIX

In [17]:
MATRIX = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
MATRIX

tensor(1)

# 4. TENSOR

In [20]:
TENSOR = torch.tensor ([[[1, 2, 3],
                         [1, 2, 3],
                         [1, 2, 3]]])
TENSOR.shape

torch.Size([1, 3, 3])

# 5. RANDOM TENSOR

In [29]:
random_tensor = torch.rand(3, 5)
random_tensor

tensor([[0.1277, 0.5498, 0.3277, 0.2241, 0.1260],
        [0.7250, 0.2331, 0.0108, 0.2413, 0.3419],
        [0.2411, 0.5736, 0.5692, 0.4443, 0.3409]])

# 6. ZEROES & ONES

In [27]:
zero_tensor = torch.zeros(3, 3)
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [28]:
one_tensor = torch.ones(3, 3)
one_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [30]:
like_tensor = torch.zeros_like(random_tensor)
like_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

# RANGE

In [31]:
range_tensor = torch.arange(1, 11, 1)
range_tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Tensor datatypes
# Tensor datatypes is one of the 3 big error we will run on.
1. Tensor not right datatype
2. Tensor not right shape
3. tensor not on the right device

In [32]:
# FLOAT 32 tensor
float_32_tensor = torch.tensor ([3.0, 6.0, 9.0], dtype=None, # datatype of tensor (default is float32, but we will also use float16)
                                                device=None, # (default cpu) What device is your tensor on
                                                requires_grad=False) # wheter or not to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [34]:
float_32_tensor.dtype

torch.float32

In [37]:
float_16_tensor = float_32_tensor.type(dtype=torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [38]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [39]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1821, 0.7621, 0.5222, 0.9972],
        [0.3748, 0.4510, 0.0557, 0.1184],
        [0.6270, 0.9061, 0.9803, 0.6534]])

In [40]:
# Find out details about this tensor
print(some_tensor)
print(f"Datatype of this tensor: {some_tensor.dtype}")
print(f"Shape of this tensor: {some_tensor.shape}")
print(f"This tensor is run on device: {some_tensor.device}")


tensor([[0.1821, 0.7621, 0.5222, 0.9972],
        [0.3748, 0.4510, 0.0557, 0.1184],
        [0.6270, 0.9061, 0.9803, 0.6534]])
Datatype of this tensor: torch.float32
Shape of this tensor: torch.Size([3, 4])
This tensor is run on device: cpu


### Manipulating tensors

It includes:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [42]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 100

tensor([101, 102, 103])

In [43]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [45]:
# Subtract by 10
tensor - 10

tensor([-9, -8, -7])

In [46]:
# Divide by 10
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

### Matrix multiplication

TWo main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [48]:
# element wise mul
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [49]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [50]:
# matrix multiplication by hand
1*1 + 2*2 + 3*3


14

In [51]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 943 µs, sys: 15 µs, total: 958 µs
Wall time: 2.65 ms


tensor(14)

In [52]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 495 µs, sys: 30 µs, total: 525 µs
Wall time: 400 µs


tensor(14)

### Comon error in deep learning : Shape errors
1. Inner dimensions MUST match for example (3,2), (2,3), this doesnt: (3,2)(3,2)
2. The resulting matrix has shape of the outer dimension

In [57]:
torch.rand(6, 3) @ torch.rand(3, 6)

tensor([[0.5370, 1.3221, 0.9061, 1.0489, 1.3821, 0.6050],
        [0.5804, 1.6843, 1.1087, 1.2964, 1.6271, 0.8340],
        [0.1548, 0.4629, 0.3064, 0.3317, 0.4342, 0.2513],
        [0.4759, 1.1596, 0.8139, 0.8205, 1.1877, 0.6135],
        [0.7269, 1.9985, 1.3404, 1.5044, 1.9650, 1.0073],
        [0.3134, 0.9278, 0.6235, 0.6184, 0.8598, 0.5421]])

In [60]:
tensor_A = torch.rand(2,3)
tensor_B = torch.rand(2,3)

tensor_A @ tensor_B.T

tensor([[0.1049, 0.3327],
        [0.4948, 0.6572]])

### Finding the min,max,mean,sum (tensor aggregation)

In [62]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [63]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [64]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [67]:
# FLoat.mean requires float datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [68]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [69]:
# Finding the positional min and max
x.argmin()

tensor(0)

In [70]:
x.argmax()

tensor(9)

## REshaping, stakcing, squeezing, and unsqieesing tensors

* Reshape - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (Vstack) or side by side (hstack)
* sqeeze - removes all `1` dimensions from a tensor
* unsqeeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a ceratin way

In [72]:
# Lets create a tensor
import torch
x = torch.arange(1., 10.)
x.shape, x

(torch.Size([9]), tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [77]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [79]:
# Change the view 
z = x.view(1,9) # Now z and x shares the same memory because it is like an alias (&) reference
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [81]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [82]:
# torch.permute, permutted shares the same memory as original
x_original = torch.rand(224,224,3) # [height, width, color_channels]

#premute the original tensor to rearange the axis
x_permuted = x_original.permute(2, 0, 1)
x_permuted.shape


torch.Size([3, 224, 224])

## INDEXING

In [83]:
#create torch
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [84]:
# Let's index on our new tensor
x[0]


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [86]:
x[:, 2, 2]

tensor([9])

## PYTORCH tensors & Numpy

`torch.from_numpy(ndarray)`
`torch.Tensor.numpy()`


In [87]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0) # Numpy default dtype is float64
tensor = torch.from_numpy(array) # But tensor torch default is float32
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

## Reproducibility (random out of random)

TO reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Esentially what it does is "flavour" of the randomness

In [89]:
import torch
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0328, 0.2347, 0.3543, 0.8360],
        [0.0916, 0.0357, 0.0023, 0.8752],
        [0.9350, 0.7659, 0.8753, 0.7671]])
tensor([[0.3304, 0.1297, 0.6545, 0.6051],
        [0.3778, 0.5979, 0.7740, 0.1354],
        [0.9384, 0.9487, 0.6869, 0.2984]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [91]:
#LEt's make some random but reproducible tensors
import torch

#Set random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### USING GPU
1. Using google colab - free gpu resources
2. Use your own GPU - takes a little bit of setup and requires the invesment of purchasing a GPU
3. Use cloud computeing, GCP, AWS, Azure.

In [3]:
# Getting GPU
!nvidia-smi

Fri Apr 21 13:02:00 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8    12W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [93]:
import torch
torch.cuda.is_available()

False

In [94]:
#Create a random tensor with shape (7,7)
SEED = torch.manual_seed(0)
tensor_a = torch.rand(7,7)
tensor_a.shape

torch.Size([7, 7])

In [96]:
#Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
tensor_b = torch.rand(1,7)
torch.matmul(tensor_a, tensor_b.T)

tensor([[2.2000],
        [1.6244],
        [1.5802],
        [2.2762],
        [2.3091],
        [0.7748],
        [2.1145]])

In [2]:
#Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? 
#(hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.
import torch
torch.cuda.is_available()


True

In [4]:
torch.cuda.manual_seed(1234)

In [5]:
#Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). 
# Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

device = torch.device('cuda')
torch.manual_seed(1234)
tensora = torch.rand(2, 3, device=device)
torch.manual_seed(1234)
tensorb = torch.rand(2, 3, device=device)

In [8]:
#Perform matmul in 6
tensorc = tensora @ tensorb.T

In [9]:
torch.max(tensorc)

tensor(1.4578, device='cuda:0')

In [10]:
torch.min(tensorc)

tensor(0.8358, device='cuda:0')

In [11]:
torch.argmin(tensorc)
torch.argmax(tensorc)

tensor(3, device='cuda:0')

In [12]:
torch.manual_seed(7)
random_last = torch.rand(1, 1, 1, 10)
random_squeezed = torch.squeeze(random_last)

print(random_last, random_last.shape)
print(random_squeezed, random_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
